title: Ian Char
position: Ph.D. Student
affiliation: Carnegie Mellon University
email: ichar (at) cs.cmu.edu
keywords: Ian Char phd student
google_scholar: https://scholar.google.com/citations?user=3SDKldkAAAAJ&hl=en
github_link: https://github.com/IanChar
cv: pdf/cv.pdf
linkedin: https://www.linkedin.com/in/ian-char-88399482/
avatar: ./assets/img/me.jpeg
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: Ian Char's personal website.
canonical: http://ianchar.com
remote_theme: yaoyao-liu/minimal-light
