title: Ian Char
position: Machine Learning Scientist
affiliation: Lila Sciences
email:
keywords: Ian Char
google_scholar: https://scholar.google.com/citations?user=3SDKldkAAAAJ&hl=en
github_link: https://github.com/IanChar
cv: pdf/cv.pdf
linkedin: https://www.linkedin.com/in/ian-char-88399482/
avatar: ./assets/img/me.jpeg
google_analytics: UA-111540567-4
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: Ian Char's personal website.
canonical: http://ianchar.com
remote_theme: yaoyao-liu/minimal-light
